openapi: 3.0.3
info:
  title: Mediatek
  description: ""
  termsOfService: http://swagger.io/terms/
  contact:
    email: leofelixpro22@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: Operations about users
  - name: albums
    description: Operation about albums
  - name: books
    description: Operation about books
  - name: movies
    description: Operation about movies
  - name: games
    description: Operation about games
paths:
  /media/albums:
    post:
      tags:
        - albums
      summary: Add a new album to the mediatek
      description: Add a new album to the mediatek
      operationId: AddMediaAlbum
      responses:
        '200':
          description: Successful operation
     
  /media/albums/{albumId}:
    get:
      tags:
        - albums
      summary: Find album by ID
      description: Returns a single album
      operationId: getMediaAlbumById
      parameters:
        - name: albumId
          in: path
          description: ID of album to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - albums
      summary: Update an existing album to the mediatek
      description: Update an existing album by Id to the mediatek
      operationId: updateMediaAlbum
      parameters:
        - name: albumId
          in: path
          description: ID of album to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - albums
      summary: Delete an existing album to the mediatek
      description: Delete an existing album by Id to the mediatek
      operationId: deleteMediaAlbum
      parameters:
        - name: albumId
          in: path
          description: ID of album to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    
  /media/books:
    post:
      tags:
        - books
      summary: Add a new book to the mediatek
      description: Add a new book to the mediatek
      operationId: AddMediaBook
      responses:
        '200':
          description: Successful operation
     
  /media/books/{bookId}:
    get:
      tags:
        - books
      summary: Find book by ID
      description: Returns a single book
      operationId: getMediaBookById
      parameters:
        - name: bookId
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - books
      summary: Update an existing book to the mediatek
      description: Update an existing book by Id to the mediatek
      operationId: updateMediaBook
      parameters:
        - name: bookId
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - books
      summary: Delete an existing book to the mediatek
      description: Delete an existing book by Id to the mediatek
      operationId: deleteMediaBook
      parameters:
        - name: bookId
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation

  /media/movies:
    post:
      tags:
        - movies
      summary: Add a new movie to the mediatek
      description: Add a new movie to the mediatek
      operationId: AddMediaMovie
      responses:
        '200':
          description: Successful operation
     
  /media/movies/{movieId}:
    get:
      tags:
        - movies
      summary: Find movie by ID
      description: Returns a single movie
      operationId: getMediaMovieById
      parameters:
        - name: movieId
          in: path
          description: ID of movie to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - movies
      summary: Update an existing movie to the mediatek
      description: Update an existing movie by Id to the mediatek
      operationId: updateMediaMovie
      parameters:
        - name: movieId
          in: path
          description: ID of movie to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - movies
      summary: Delete an existing movie to the mediatek
      description: Delete an existing movie by Id to the mediatek
      operationId: deleteMediaMovie
      parameters:
        - name: movieId
          in: path
          description: ID of movie to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation

  /media/games:
    post:
      tags:
        - games
      summary: Add a new game to the mediatek
      description: Add a new game to the mediatek
      operationId: AddMediaGame
      responses:
        '200':
          description: Successful operation
     
  /media/games/{gameId}:
    get:
      tags:
        - games
      summary: Find game by ID
      description: Returns a single game
      operationId: getMediaGameById
      parameters:
        - name: gameId
          in: path
          description: ID of game to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - games
      summary: Update an existing game to the mediatek
      description: Update an existing game by Id to the mediatek
      operationId: updateMediaGame
      parameters:
        - name: gameId
          in: path
          description: ID of game to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - games
      summary: Delete an existing game to the mediatek
      description: Delete an existing game by Id to the mediatek
      operationId: deleteMediaGame
      parameters:
        - name: gameId
          in: path
          description: ID of game to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
  